# Generated by Django 5.2.3 on 2025-06-18 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_course_donecareer_lesson'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='file_url',
            field=models.FileField(upload_to='lessons/'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(max_length=100),
        ),
    ]
