# Generated by Django 5.2.3 on 2025-06-18 13:23

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_lesson_file_url_alter_lesson_video_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DoneCareer',
            new_name='DoneCourse',
        ),
    ]
