# Generated by Django 5.2.3 on 2025-06-19 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_rename_donecareer_donecourse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.FileField(upload_to='lesson_videos/'),
        ),
    ]
