# Generated by Django 5.2.3 on 2025-06-19 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_alter_lesson_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donecourse',
            old_name='end_career',
            new_name='end_course',
        ),
    ]
