# Generated by Django 5.2.3 on 2025-06-19 12:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_lesson_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donecourse',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='donecourse',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
