# Generated by Django 5.2.3 on 2025-06-19 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_rename_course_id_donecourse_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donecourse',
            old_name='course',
            new_name='course_id',
        ),
        migrations.RenameField(
            model_name='donecourse',
            old_name='user',
            new_name='user_id',
        ),
    ]
