# Generated by Django 5.2.3 on 2025-06-19 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_rename_course_donecourse_course_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donecourse',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='donecourse',
            old_name='user_id',
            new_name='user',
        ),
    ]
