# Generated by Django 5.2.3 on 2025-06-21 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0005_alter_certificate_code'),
        ('quiz', '0012_rename_course_id_donecourse_course_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testresult',
            old_name='test_id',
            new_name='test',
        ),
        migrations.RenameField(
            model_name='testresult',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='testresult',
            name='ai_analysis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='certificate.certificate'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='result_scale',
            field=models.TextField(blank=True, null=True),
        ),
    ]
