# Generated by Django 5.2.3 on 2025-06-21 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0013_rename_test_id_testresult_test_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='test',
            name='careers_id',
        ),
        migrations.RemoveField(
            model_name='testitem',
            name='type_id',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='certificate',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='result_scale',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='score',
        ),
    ]
