# Generated by Django 5.2.3 on 2025-06-21 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0014_remove_question_test_id_remove_test_careers_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='test_item_id',
            new_name='test_item',
        ),
        migrations.RenameField(
            model_name='answer',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='body',
            old_name='roadmaps_id',
            new_name='roadmaps',
        ),
        migrations.RenameField(
            model_name='lesson',
            old_name='course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='options',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='testitem',
            old_name='question_id',
            new_name='question',
        ),
        migrations.RenameField(
            model_name='testitem',
            old_name='test_id',
            new_name='test',
        ),
    ]
