# Generated by Django 5.2.3 on 2025-06-21 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0015_rename_test_item_id_answer_test_item_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='body',
            old_name='roadmaps',
            new_name='roadmaps_id',
        ),
    ]
