# Generated by Django 5.2.3 on 2025-06-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_rename_user_answer_user_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careers',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='careers'),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
