# Generated by Django 5.2.3 on 2025-06-21 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0018_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='testitem',
            name='career',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.careers'),
        ),
    ]
